[workspace]
resolver = "3"
members = ["frozone","frozone-derive"]


[workspace.dependencies]
proc-macro2 = { version = "1.0.106", default-features = false }
quote = { version = "1.0.44", default-features = false }
syn = { version = "2.0.114", default-features = false }
